### ISSUE TITLE
Migrate to iDynTree + RemoteControlBoardRemapper

### ISSUE THREAD

**Issue by traversaro** [vvv-school/tutorial_impedance-control#1]

**Comment by diegoferigo** [comment]
Currently `iDynTree` and `RemoteControlBoardRemapper` resources are handled by the toolbox with the [`RobotInterface`](https://github.com/robotology/WB-Toolbox/blob/WB3.0/toolbox/include/base/RobotInterface.h) class. In this case, it would be the perfect replacement for the deprecated `yarpWholeBodyInterface`.

However, the `WB3.0` branch which is installed in the VM still compiles the mex monolithic-ally. The `WB3.1` instead will export the toolbox as a library, and it links it against simulink-related piece of software in a later moment.

Probably the best option for this year's VVV is using the raw resources, and we might consider switching to `RobotInterface` next year in order to simplify the tutorials / assignments code.

What do you think @traversaro?

**Comment by diegoferigo** [comment]
A viable alternative would be quickly porting this new CMake logic in the `WB3.0`, it wouldn't take a lot considering it is already done for `WB3.1`. At that point, a simple `find_package()` would do the work.

If we proceed in this way, we can open an issue and ask all the students to update the toolbox before Saturday.

**Comment by traversaro** [comment]
Done in https://github.com/vvv-school/tutorial_impedance-control/pull/2 .
