### ISSUE TITLE
iCub falls face down

### ISSUE THREAD

**Issue by atabakd** [vvv-school/tutorial_impedance-control#3]
I have been trying to get this demo to work again, but I cannot remember which iCub model we were using. It works if I use "iCubGazeboV2_5 fixed" but icub falls on the ground if I use "iCubGazeboV2_5 standing".
I am not sure if this was the expected behaviour :thinking: 
Cheers,

**Comment by pattacini** [comment]
cc @diegoferigo @traversaro

**Comment by diegoferigo** [comment]
Usually when if falls down it means that `gazebo-yarp-plugins` are either missing or not properly loaded / configured.

In the past this happened to me when `yarp` and `gazebo-yarp-plugins` were checked out on different branches. Both should be either `master` or `devel`.

@atabakd be careful of branches because last week we did a new release of all the software. Be sure all the repositories use `master` (`WB-Toolbox` included).

You can get useful information executing gazebo with `--verbose`.

**Comment by atabakd** [comment]
Thanks for pointing that out. I'll start recompiling everything :wink:. But I saw this behaviour even on my VM where I did not upgrade/change installations.

**Comment by atabakd** [comment]
Well, I just checked the app and I saw that gazebo server starts with the parameter `icub_simple_fixed_world/icub_simple_fixed.world` meaning that probably we use a fixed model of the iCub. It also makes sense because this controller only compensates for the gravity and there is no stabilization of the centre of the mass.
